In [2]:
import numpy as np


z = 2.0
dist = 10.0

rbf = np.exp(-(z * dist) ** 2)
rbf

np.float64(1.9151695967140057e-174)

In [10]:
def _mother_function(r: np.ndarray, r0: float) -> np.ndarray:
        return np.exp(-0.5 * (r / r0) ** 2)

def compute_weights(dists: np.ndarray, z) -> np.ndarray:
    r0 = z
    weights = _mother_function(dists, r0=r0)

    phi_sum = np.sum(weights)
    if phi_sum == 0:
        return np.ones(len(dists)) / len(dists)  # fallback uniforme

    weights /= phi_sum  # particao de unidade
    return weights

dists = np.array([0.0, 10.0, 20.0, 30.0])
print(compute_weights(dists=dists,z= 1.0))
print(compute_weights(dists=dists,z= 2.0))
print(compute_weights(dists=dists,z= 10.0))

[1.00000000e+000 1.92874985e-022 1.38389653e-087 3.69388307e-196]
[9.99996273e-01 3.72663928e-06 1.92874266e-22 1.38633813e-49]
[0.57045881 0.34600076 0.0772032  0.00633722]
